
/*
 * 
 */

package bookStore;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 18 11:20:12 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "BookStoreService", 
                  wsdlLocation = "file:/home/tomy/NetBeansProjects/AOS-labs/lab05BookStoreTopToDown/src/main/java/BookStore.wsdl",
                  targetNamespace = "http://j2ee.netbeans.org/wsdl/lab05BookStoreTopToDown/java/BookStore") 
public class BookStoreService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://j2ee.netbeans.org/wsdl/lab05BookStoreTopToDown/java/BookStore", "BookStoreService");
    public final static QName BookStorePort = new QName("http://j2ee.netbeans.org/wsdl/lab05BookStoreTopToDown/java/BookStore", "BookStorePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/tomy/NetBeansProjects/AOS-labs/lab05BookStoreTopToDown/src/main/java/BookStore.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/tomy/NetBeansProjects/AOS-labs/lab05BookStoreTopToDown/src/main/java/BookStore.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BookStoreService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookStoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookStoreService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BookStoreService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public BookStoreService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BookStoreService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookStorePortType
     */
    @WebEndpoint(name = "BookStorePort")
    public BookStorePortType getBookStorePort() {
        return super.getPort(BookStorePort, BookStorePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookStorePortType
     */
    @WebEndpoint(name = "BookStorePort")
    public BookStorePortType getBookStorePort(WebServiceFeature... features) {
        return super.getPort(BookStorePort, BookStorePortType.class, features);
    }

}
