
package bookStore;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 18 11:20:11 CEST 2012
 * Generated source version: 2.3.1
 * 
 */
 
public class BookStorePortType_BookStorePort_Server{

    protected BookStorePortType_BookStorePort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new BookStorePortTypeImpl();
        String address = "http://localhost:${HttpDefaultPort}/BookStoreService/BookStorePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new BookStorePortType_BookStorePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
