
package concat;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 18 09:43:07 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

public final class ConcatService_ConcatSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/NewWSDLFile/", "ConcatWSDL");

    private ConcatService_ConcatSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ConcatWSDL.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConcatWSDL ss = new ConcatWSDL(wsdlURL, SERVICE_NAME);
        ConcatService port = ss.getConcatSOAP();  
        
        {
        System.out.println("Invoking concatOperation...");
        concat.Concat _concatOperation_parameters = new Concat();
        _concatOperation_parameters.setString1("Tomas");
        _concatOperation_parameters.setString2("Mano");
        String _concatOperation__return = port.concatOperation(_concatOperation_parameters.getString1(), _concatOperation_parameters.getString2());
        System.out.println("concatOperation.result=" + _concatOperation__return);


        }

        System.exit(0);
    }

}
