
package concat;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 18 09:57:30 CEST 2012
 * Generated source version: 2.3.1
 * 
 */
 
public class ConcatService_ConcatSOAP_Server{

    protected ConcatService_ConcatSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ConcatServiceImpl();
        String address = "http://localhost:8081/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ConcatService_ConcatSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
