
/*
 * 
 */

package cz.cvut.aos.bookingserver.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Nov 22 17:33:26 CET 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "BookingServiceImplService", 
                  wsdlLocation = "http://localhost:8081/BookingServer/BookingService?wsdl",
                  targetNamespace = "http://webservice.bookingserver.aos.cvut.cz/") 
public class BookingServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.bookingserver.aos.cvut.cz/", "BookingServiceImplService");
    public final static QName BookingServiceImplPort = new QName("http://webservice.bookingserver.aos.cvut.cz/", "BookingServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/BookingServer/BookingService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8081/BookingServer/BookingService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BookingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BookingServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public BookingServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BookingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "BookingServiceImplPort")
    public BookingService getBookingServiceImplPort() {
        return super.getPort(BookingServiceImplPort, BookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "BookingServiceImplPort")
    public BookingService getBookingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BookingServiceImplPort, BookingService.class, features);
    }

}
