
/*
 * 
 */

package edu.tomy.aoslab04;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 11 12:00:26 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "BookServiceInMemoryImplService", 
                  wsdlLocation = "http://localhost:8080/aos-lab04/BookService?wsdl",
                  targetNamespace = "http://aoslab04.tomy.edu/") 
public class BookServiceInMemoryImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://aoslab04.tomy.edu/", "BookServiceInMemoryImplService");
    public final static QName BookServiceInMemoryImplPort = new QName("http://aoslab04.tomy.edu/", "BookServiceInMemoryImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/aos-lab04/BookService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/aos-lab04/BookService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BookServiceInMemoryImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookServiceInMemoryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookServiceInMemoryImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BookServiceInMemoryImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public BookServiceInMemoryImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BookServiceInMemoryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookServiceInMemoryImplPort")
    public BookService getBookServiceInMemoryImplPort() {
        return super.getPort(BookServiceInMemoryImplPort, BookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookServiceInMemoryImplPort")
    public BookService getBookServiceInMemoryImplPort(WebServiceFeature... features) {
        return super.getPort(BookServiceInMemoryImplPort, BookService.class, features);
    }

}
