package edu.tomy.aoslab04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 11 12:00:26 CEST 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://aoslab04.tomy.edu/", name = "BookService")
@XmlSeeAlso({ObjectFactory.class})
public interface BookService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.AddBook")
    @WebMethod
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.AddBookResponse")
    public boolean addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        edu.tomy.aoslab04.Book arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "removeBook", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.RemoveBook")
    @WebMethod
    @ResponseWrapper(localName = "removeBookResponse", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.RemoveBookResponse")
    public boolean removeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchBookByTitle", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.SearchBookByTitle")
    @WebMethod
    @ResponseWrapper(localName = "searchBookByTitleResponse", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.SearchBookByTitleResponse")
    public java.util.List<edu.tomy.aoslab04.Book> searchBookByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchBookByAuthor", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.SearchBookByAuthor")
    @WebMethod
    @ResponseWrapper(localName = "searchBookByAuthorResponse", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.SearchBookByAuthorResponse")
    public java.util.List<edu.tomy.aoslab04.Book> searchBookByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAllBooks", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.ListAllBooks")
    @WebMethod
    @ResponseWrapper(localName = "listAllBooksResponse", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.ListAllBooksResponse")
    public java.util.List<edu.tomy.aoslab04.Book> listAllBooks();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.UpdateBook")
    @WebMethod
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://aoslab04.tomy.edu/", className = "edu.tomy.aoslab04.UpdateBookResponse")
    public boolean updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );
}
