
package division;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 09:32:36 CEST 2012
 * Generated source version: 2.3.1
 * 
 */
 
public class DivisionServiceIface_DivisionServicePort_Server{

    protected DivisionServiceIface_DivisionServicePort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new DivisionServiceIfaceImpl();
        String address = "http://localhost:8083/cxf_spring/DivisionService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new DivisionServiceIface_DivisionServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
