
/*
 * 
 */

package division;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 09:32:36 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "DivisionServiceService", 
                  wsdlLocation = "file:/home/tomy/NetBeansProjects/AOS-labs/lab06/lab06division/src/main/resources/division.xml",
                  targetNamespace = "http://testing/") 
public class DivisionServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://testing/", "DivisionServiceService");
    public final static QName DivisionServicePort = new QName("http://testing/", "DivisionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/tomy/NetBeansProjects/AOS-labs/lab06/lab06division/src/main/resources/division.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/tomy/NetBeansProjects/AOS-labs/lab06/lab06division/src/main/resources/division.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DivisionServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DivisionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DivisionServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DivisionServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public DivisionServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DivisionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DivisionServiceIface
     */
    @WebEndpoint(name = "DivisionServicePort")
    public DivisionServiceIface getDivisionServicePort() {
        return super.getPort(DivisionServicePort, DivisionServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DivisionServiceIface
     */
    @WebEndpoint(name = "DivisionServicePort")
    public DivisionServiceIface getDivisionServicePort(WebServiceFeature... features) {
        return super.getPort(DivisionServicePort, DivisionServiceIface.class, features);
    }

}
