
package division;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 09:32:36 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "DivisionByZeroException", targetNamespace = "http://testing/")
public class DivisionByZeroException_Exception extends Exception {
    public static final long serialVersionUID = 20121025093236L;
    
    private division.DivisionByZeroException divisionByZeroException;

    public DivisionByZeroException_Exception() {
        super();
    }
    
    public DivisionByZeroException_Exception(String message) {
        super(message);
    }
    
    public DivisionByZeroException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DivisionByZeroException_Exception(String message, division.DivisionByZeroException divisionByZeroException) {
        super(message);
        this.divisionByZeroException = divisionByZeroException;
    }

    public DivisionByZeroException_Exception(String message, division.DivisionByZeroException divisionByZeroException, Throwable cause) {
        super(message, cause);
        this.divisionByZeroException = divisionByZeroException;
    }

    public division.DivisionByZeroException getFaultInfo() {
        return this.divisionByZeroException;
    }
}
