
/*
 * 
 */

package simplefileserver.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Nov 08 10:45:07 CET 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "ConcatServiceImplService", 
                  wsdlLocation = "http://localhost:8082/?wsdl",
                  targetNamespace = "http://server.concatsecuritydemo/") 
public class ConcatServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://server.concatsecuritydemo/", "ConcatServiceImplService");
    public final static QName ConcatServiceImplPort = new QName("http://server.concatsecuritydemo/", "ConcatServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8082/?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8082/?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ConcatServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConcatServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConcatServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ConcatServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public ConcatServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConcatServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConcatService
     */
    @WebEndpoint(name = "ConcatServiceImplPort")
    public ConcatService getConcatServiceImplPort() {
        return super.getPort(ConcatServiceImplPort, ConcatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConcatService
     */
    @WebEndpoint(name = "ConcatServiceImplPort")
    public ConcatService getConcatServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ConcatServiceImplPort, ConcatService.class, features);
    }

}
