package simplefileserver.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Nov 08 10:45:07 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://www.example.org/NewWSDLFile/", name = "concatService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConcatService {

    @WebResult(name = "concatResponse", targetNamespace = "http://www.example.org/NewWSDLFile/", partName = "parameters")
    @WebMethod(operationName = "ConcatOperation", action = "http://www.example.org/NewWSDLFile/ConcatOperation")
    public ConcatResponse concatOperation(
        @WebParam(partName = "parameters", name = "concat", targetNamespace = "http://www.example.org/NewWSDLFile/")
        Concat parameters
    );
}
