package filesending.mime.server;

import javax.xml.ws.soap.SOAPBinding;
import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1 Thu Oct 25 10:21:11 CEST 2012
 * Generated source version: 2.3.1
 *
 */
public class SendFileIface_SendFilePort_Server {

    protected SendFileIface_SendFilePort_Server() throws Exception {



        System.out.println("Starting Server");
        Object implementor = new SendFileIfaceImpl();
        String address = "http://localhost:8077/cxf_spring/SendFile";
        Endpoint endpoint = Endpoint.publish(address, implementor);
        
        ((SOAPBinding)endpoint.getBinding()).setMTOMEnabled(true);
        
    }

    public static void main(String args[]) throws Exception {
        new SendFileIface_SendFilePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(10 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
