
/*
 * 
 */

package filesending.mime.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 10:21:11 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SendFileService", 
                  wsdlLocation = "file:/home/tomy/NetBeansProjects/AOS-labs/lab06/lab06filesending/src/main/resources/filesending-mime.xml",
                  targetNamespace = "http://testing/") 
public class SendFileService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://testing/", "SendFileService");
    public final static QName SendFilePort = new QName("http://testing/", "SendFilePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/tomy/NetBeansProjects/AOS-labs/lab06/lab06filesending/src/main/resources/filesending-mime.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/tomy/NetBeansProjects/AOS-labs/lab06/lab06filesending/src/main/resources/filesending-mime.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SendFileService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendFileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendFileService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SendFileService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public SendFileService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SendFileService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendFileIface
     */
    @WebEndpoint(name = "SendFilePort")
    public SendFileIface getSendFilePort() {
        return super.getPort(SendFilePort, SendFileIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendFileIface
     */
    @WebEndpoint(name = "SendFilePort")
    public SendFileIface getSendFilePort(WebServiceFeature... features) {
        return super.getPort(SendFilePort, SendFileIface.class, features);
    }

}
