
package simplefileserver.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Oct 28 18:37:02 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "NoSuchFile", targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server")
public class NoSuchFileExceptionException extends Exception {
    public static final long serialVersionUID = 20121028183702L;
    
    private simplefileserver.client.NoSuchFileException noSuchFile;

    public NoSuchFileExceptionException() {
        super();
    }
    
    public NoSuchFileExceptionException(String message) {
        super(message);
    }
    
    public NoSuchFileExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchFileExceptionException(String message, simplefileserver.client.NoSuchFileException noSuchFile) {
        super(message);
        this.noSuchFile = noSuchFile;
    }

    public NoSuchFileExceptionException(String message, simplefileserver.client.NoSuchFileException noSuchFile, Throwable cause) {
        super(message, cause);
        this.noSuchFile = noSuchFile;
    }

    public simplefileserver.client.NoSuchFileException getFaultInfo() {
        return this.noSuchFile;
    }
}
