package simplefileserver.client;

/**
 * Please modify this class to meet your needs This class is not complete
 */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.3.1 Sun Oct 28 18:37:02 CET 2012
 * Generated source version: 2.3.1
 *
 */
public final class SimpleFileServer_SimpleFileServerImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.simplefileserver/", "SimpleFileServerImplService");
    
    private static final String FILE_NAME_FOR_PUT = "deer.png";
    private static final String FILE_PATH_EXAMPLE_FOR_PUT = "/home/tomy/Pictures/simpledesktops/deer.png";
    private static final String FILE_NAME_FOR_POSTING = "zebra.png";
    private static final String FILE_PATH_EXAMPLE_FOR_POST = "/home/tomy/Pictures/simpledesktops/zebra.png";

    private SimpleFileServer_SimpleFileServerImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SimpleFileServerImplService.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SimpleFileServerImplService ss = new SimpleFileServerImplService(wsdlURL, SERVICE_NAME);
        SimpleFileServer port = ss.getSimpleFileServerImplPort();

        {
            System.out.println("Invoking deleteFile...");
            java.lang.String _deleteFile_fileName = "monalisa.png";
            try {
                java.lang.String _deleteFile__return = port.deleteFile(_deleteFile_fileName);
                System.out.println("deleteFile.result=" + _deleteFile__return);

            } catch (NoSuchFileExceptionException e) {
                System.out.println("Expected exception: NoSuchFileException_Exception has occurred.");
                System.out.println(e.toString());
            }
        }
        {
            System.out.println("Invoking getFile...");
            java.lang.String _getFile_fileName = "sailor.png";
            try {
                simplefileserver.client.BinaryFile _getFile__return = port.getFile(_getFile_fileName);
                System.out.println("getFile.result=" + _getFile__return);

            } catch (NoSuchFileExceptionException e) {
                System.out.println("Expected exception: NoSuchFileException_Exception has occurred.");
                System.out.println(e.toString());
            }
        }
        {
            System.out.println("Invoking putFile...");
            java.lang.String _putFile_filename = FILE_NAME_FOR_PUT;
            File required = new File(FILE_PATH_EXAMPLE_FOR_PUT);
            BinaryFile bf = new BinaryFile(new DataHandler(new FileDataSource(required)));
            simplefileserver.client.BinaryFile _putFile_fileFromClient = bf;
            port.putFile(_putFile_filename, _putFile_fileFromClient);


        }
        {
            System.out.println("Invoking listFiles...");
            java.math.BigInteger _listFiles_outputSize = new java.math.BigInteger("10");
            simplefileserver.client.StringArray _listFiles__return = port.listFiles(_listFiles_outputSize);
            System.out.println("listFiles.result=" + _listFiles__return);


        }
        {
            System.out.println("Invoking postFile...");
            java.lang.String _postFile_filename = FILE_NAME_FOR_POSTING;
            File required = new File(FILE_PATH_EXAMPLE_FOR_POST);
            BinaryFile bf = new BinaryFile(new DataHandler(new FileDataSource(required)));
            simplefileserver.client.BinaryFile _postFile_file = bf;
            try {
                java.lang.String _postFile__return = port.postFile(_postFile_filename, _postFile_file);
                System.out.println("postFile.result=" + _postFile__return);

            } catch (NoSuchFileExceptionException e) {
                System.out.println("Expected exception: NoSuchFileException_Exception has occurred.");
                System.out.println(e.toString());
            }
        }

        System.exit(0);
    }
}
