package simplefileserver.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Oct 28 18:37:02 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server", name = "simple-file-server")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SimpleFileServer {

    @WebResult(name = "legacyResponse", targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server", partName = "legacyResponse")
    @WebMethod
    public java.lang.String deleteFile(
        @WebParam(partName = "fileName", name = "fileName")
        java.lang.String fileName
    ) throws NoSuchFileExceptionException;

    @WebResult(name = "fileFromServer", targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server", partName = "fileFromServer")
    @WebMethod
    public BinaryFile getFile(
        @WebParam(partName = "fileName", name = "fileName")
        java.lang.String fileName
    ) throws NoSuchFileExceptionException;

    @Oneway
    @WebMethod
    public void putFile(
        @WebParam(partName = "filename", name = "filename")
        java.lang.String filename,
        @WebParam(partName = "fileFromClient", name = "fileFromClient")
        BinaryFile fileFromClient
    );

    @WebResult(name = "listOfFilenames", targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server", partName = "listOfFilenames")
    @WebMethod
    public StringArray listFiles(
        @WebParam(partName = "outputSize", name = "outputSize")
        java.math.BigInteger outputSize
    );

    @WebResult(name = "legacyResponse", targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server", partName = "legacyResponse")
    @WebMethod
    public java.lang.String postFile(
        @WebParam(partName = "filename", name = "filename")
        java.lang.String filename,
        @WebParam(partName = "file", name = "file")
        BinaryFile file
    ) throws NoSuchFileExceptionException;
}
