
package simplefileserver.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Oct 28 17:59:54 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "NoSuchFile", targetNamespace = "http://j2ee.netbeans.org/wsdl/lab06simplefileserver/java/simple-file-server")
public class NoSuchFileException_Exception extends Exception {
    public static final long serialVersionUID = 20121028175954L;
    
    private simplefileserver.server.NoSuchFileException noSuchFile;

    public NoSuchFileException_Exception() {
        super();
    }
    
    public NoSuchFileException_Exception(String message) {
        super(message);
    }
    
    public NoSuchFileException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchFileException_Exception(String message, simplefileserver.server.NoSuchFileException noSuchFile) {
        super(message);
        this.noSuchFile = noSuchFile;
    }

    public NoSuchFileException_Exception(String message, simplefileserver.server.NoSuchFileException noSuchFile, Throwable cause) {
        super(message, cause);
        this.noSuchFile = noSuchFile;
    }

    public simplefileserver.server.NoSuchFileException getFaultInfo() {
        return this.noSuchFile;
    }
}
