
package simplefileserver.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Oct 28 17:59:54 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
public class SimpleFileServer_FileServerServicesPort_Server{

    protected SimpleFileServer_FileServerServicesPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new SimpleFileServerImpl();
        String address = "http://localhost:8082/cxf_spring/SimpleFileServer";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new SimpleFileServer_FileServerServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(20 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
