package generatedcode.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sat Nov 03 15:36:47 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://footballpool.dataaccess.eu", name = "InfoSoapType")
@XmlSeeAlso({ObjectFactory.class})
public interface InfoSoapType {

    @WebResult(name = "TopGoalScorersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "TopGoalScorers", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TopGoalScorers")
    @WebMethod(operationName = "TopGoalScorers")
    @ResponseWrapper(localName = "TopGoalScorersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TopGoalScorersResponse")
    public generatedcode.client.ArrayOftTopGoalScorer topGoalScorers(
        @WebParam(name = "iTopN", targetNamespace = "http://footballpool.dataaccess.eu")
        int iTopN
    );

    @WebResult(name = "GamesPlayedResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GamesPlayed", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GamesPlayed")
    @WebMethod(operationName = "GamesPlayed")
    @ResponseWrapper(localName = "GamesPlayedResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GamesPlayedResponse")
    public int gamesPlayed();

    @WebResult(name = "DateLastGroupGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "DateLastGroupGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.DateLastGroupGame")
    @WebMethod(operationName = "DateLastGroupGame")
    @ResponseWrapper(localName = "DateLastGroupGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.DateLastGroupGameResponse")
    public javax.xml.datatype.XMLGregorianCalendar dateLastGroupGame();

    @WebResult(name = "AllStadiumInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllStadiumInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllStadiumInfo")
    @WebMethod(operationName = "AllStadiumInfo")
    @ResponseWrapper(localName = "AllStadiumInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllStadiumInfoResponse")
    public generatedcode.client.ArrayOftStadiumInfo allStadiumInfo();

    @WebResult(name = "SignupsPerDateResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "SignupsPerDate", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.SignupsPerDate")
    @WebMethod(operationName = "SignupsPerDate")
    @ResponseWrapper(localName = "SignupsPerDateResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.SignupsPerDateResponse")
    public generatedcode.client.ArrayOftSignupCount signupsPerDate();

    @WebResult(name = "AllForwardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllForwards", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllForwards")
    @WebMethod(operationName = "AllForwards")
    @ResponseWrapper(localName = "AllForwardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllForwardsResponse")
    public generatedcode.client.ArrayOfString allForwards(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    @WebResult(name = "AllPlayerNamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllPlayerNames", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayerNames")
    @WebMethod(operationName = "AllPlayerNames")
    @ResponseWrapper(localName = "AllPlayerNamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayerNamesResponse")
    public generatedcode.client.ArrayOftPlayerNames allPlayerNames(
        @WebParam(name = "bSelected", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSelected
    );

    @WebResult(name = "GroupCompetitorsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GroupCompetitors", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GroupCompetitors")
    @WebMethod(operationName = "GroupCompetitors")
    @ResponseWrapper(localName = "GroupCompetitorsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GroupCompetitorsResponse")
    public generatedcode.client.ArrayOftTeamInfo groupCompetitors(
        @WebParam(name = "sPoule", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sPoule
    );

    @WebResult(name = "StadiumInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "StadiumInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.StadiumInfo")
    @WebMethod(operationName = "StadiumInfo")
    @ResponseWrapper(localName = "StadiumInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.StadiumInfoResponse")
    public generatedcode.client.TStadiumInfo stadiumInfo(
        @WebParam(name = "sStadiumName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sStadiumName
    );

    @WebResult(name = "AllPlayersWithRedCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllPlayersWithRedCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayersWithRedCards")
    @WebMethod(operationName = "AllPlayersWithRedCards")
    @ResponseWrapper(localName = "AllPlayersWithRedCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayersWithRedCardsResponse")
    public generatedcode.client.ArrayOftPlayersWithCards allPlayersWithRedCards(
        @WebParam(name = "bSortedByName", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByName,
        @WebParam(name = "bSortedByRedCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByRedCards
    );

    @WebResult(name = "DateOfFirstGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "DateOfFirstGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.DateOfFirstGame")
    @WebMethod(operationName = "DateOfFirstGame")
    @ResponseWrapper(localName = "DateOfFirstGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.DateOfFirstGameResponse")
    public javax.xml.datatype.XMLGregorianCalendar dateOfFirstGame();

    @WebResult(name = "RedCardsTotalResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "RedCardsTotal", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.RedCardsTotal")
    @WebMethod(operationName = "RedCardsTotal")
    @ResponseWrapper(localName = "RedCardsTotalResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.RedCardsTotalResponse")
    public int redCardsTotal();

    @WebResult(name = "StadiumURLResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "StadiumURL", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.StadiumURL")
    @WebMethod(operationName = "StadiumURL")
    @ResponseWrapper(localName = "StadiumURLResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.StadiumURLResponse")
    public java.lang.String stadiumURL(
        @WebParam(name = "sStadiumName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sStadiumName
    );

    @WebResult(name = "PlayedAtWorldCupResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "PlayedAtWorldCup", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.PlayedAtWorldCup")
    @WebMethod(operationName = "PlayedAtWorldCup")
    @ResponseWrapper(localName = "PlayedAtWorldCupResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.PlayedAtWorldCupResponse")
    public int playedAtWorldCup(
        @WebParam(name = "sTeamName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sTeamName
    );

    @WebResult(name = "YellowAndRedCardsTotalResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "YellowAndRedCardsTotal", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.YellowAndRedCardsTotal")
    @WebMethod(operationName = "YellowAndRedCardsTotal")
    @ResponseWrapper(localName = "YellowAndRedCardsTotalResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.YellowAndRedCardsTotalResponse")
    public generatedcode.client.TCards yellowAndRedCardsTotal();

    @WebResult(name = "CoachesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "Coaches", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.Coaches")
    @WebMethod(operationName = "Coaches")
    @ResponseWrapper(localName = "CoachesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.CoachesResponse")
    public generatedcode.client.ArrayOftCoaches coaches();

    @WebResult(name = "GamesPerCityResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GamesPerCity", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GamesPerCity")
    @WebMethod(operationName = "GamesPerCity")
    @ResponseWrapper(localName = "GamesPerCityResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GamesPerCityResponse")
    public generatedcode.client.ArrayOftGameInfo gamesPerCity(
        @WebParam(name = "sCityName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCityName
    );

    @WebResult(name = "GameResultCodesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GameResultCodes", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GameResultCodes")
    @WebMethod(operationName = "GameResultCodes")
    @ResponseWrapper(localName = "GameResultCodesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GameResultCodesResponse")
    public generatedcode.client.ArrayOftGameResultCode gameResultCodes();

    @WebResult(name = "AllGamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllGames", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllGames")
    @WebMethod(operationName = "AllGames")
    @ResponseWrapper(localName = "AllGamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllGamesResponse")
    public generatedcode.client.ArrayOftGameInfo allGames();

    @WebResult(name = "GoalsScoredResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GoalsScored", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GoalsScored")
    @WebMethod(operationName = "GoalsScored")
    @ResponseWrapper(localName = "GoalsScoredResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GoalsScoredResponse")
    public generatedcode.client.ArrayOftGoal goalsScored(
        @WebParam(name = "iGameId", targetNamespace = "http://footballpool.dataaccess.eu")
        int iGameId
    );

    @WebResult(name = "AllGroupCompetitorsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllGroupCompetitors", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllGroupCompetitors")
    @WebMethod(operationName = "AllGroupCompetitors")
    @ResponseWrapper(localName = "AllGroupCompetitorsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllGroupCompetitorsResponse")
    public generatedcode.client.ArrayOftGroupsCompetitors allGroupCompetitors();

    @WebResult(name = "DateOfLastGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "DateOfLastGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.DateOfLastGame")
    @WebMethod(operationName = "DateOfLastGame")
    @ResponseWrapper(localName = "DateOfLastGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.DateOfLastGameResponse")
    public javax.xml.datatype.XMLGregorianCalendar dateOfLastGame();

    @WebResult(name = "GroupsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "Groups", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.Groups")
    @WebMethod(operationName = "Groups")
    @ResponseWrapper(localName = "GroupsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GroupsResponse")
    public generatedcode.client.ArrayOftGroupInfo groups();

    @WebResult(name = "AllPlayersWithYellowCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllPlayersWithYellowCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayersWithYellowCards")
    @WebMethod(operationName = "AllPlayersWithYellowCards")
    @ResponseWrapper(localName = "AllPlayersWithYellowCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayersWithYellowCardsResponse")
    public generatedcode.client.ArrayOftPlayersWithCards allPlayersWithYellowCards(
        @WebParam(name = "bSortedByName", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByName,
        @WebParam(name = "bSortedByYellowCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByYellowCards
    );

    @WebResult(name = "YellowCardsTotalResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "YellowCardsTotal", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.YellowCardsTotal")
    @WebMethod(operationName = "YellowCardsTotal")
    @ResponseWrapper(localName = "YellowCardsTotalResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.YellowCardsTotalResponse")
    public int yellowCardsTotal();

    @WebResult(name = "CitiesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "Cities", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.Cities")
    @WebMethod(operationName = "Cities")
    @ResponseWrapper(localName = "CitiesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.CitiesResponse")
    public generatedcode.client.ArrayOfString cities();

    @WebResult(name = "CountryNamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "CountryNames", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.CountryNames")
    @WebMethod(operationName = "CountryNames")
    @ResponseWrapper(localName = "CountryNamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.CountryNamesResponse")
    public generatedcode.client.ArrayOftCountryInfo countryNames(
        @WebParam(name = "bWithCompetitors", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bWithCompetitors
    );

    @WebResult(name = "TournamentInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "TournamentInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TournamentInfo")
    @WebMethod(operationName = "TournamentInfo")
    @ResponseWrapper(localName = "TournamentInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TournamentInfoResponse")
    public generatedcode.client.TTournamentInfo tournamentInfo();

    @WebResult(name = "StadiumNamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "StadiumNames", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.StadiumNames")
    @WebMethod(operationName = "StadiumNames")
    @ResponseWrapper(localName = "StadiumNamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.StadiumNamesResponse")
    public generatedcode.client.ArrayOfString stadiumNames();

    @WebResult(name = "NumberOfGamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "NumberOfGames", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.NumberOfGames")
    @WebMethod(operationName = "NumberOfGames")
    @ResponseWrapper(localName = "NumberOfGamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.NumberOfGamesResponse")
    public int numberOfGames();

    @WebResult(name = "TeamsCompeteListResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "TeamsCompeteList", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TeamsCompeteList")
    @WebMethod(operationName = "TeamsCompeteList")
    @ResponseWrapper(localName = "TeamsCompeteListResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TeamsCompeteListResponse")
    public generatedcode.client.ArrayOftTeamCompete teamsCompeteList();

    @WebResult(name = "FullTeamInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "FullTeamInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.FullTeamInfo")
    @WebMethod(operationName = "FullTeamInfo")
    @ResponseWrapper(localName = "FullTeamInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.FullTeamInfoResponse")
    public generatedcode.client.TFullTeamInfo fullTeamInfo(
        @WebParam(name = "sTeamName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sTeamName
    );

    @WebResult(name = "TeamsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "Teams", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.Teams")
    @WebMethod(operationName = "Teams")
    @ResponseWrapper(localName = "TeamsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TeamsResponse")
    public generatedcode.client.ArrayOftTeamInfo teams();

    @WebResult(name = "GroupCountResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GroupCount", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GroupCount")
    @WebMethod(operationName = "GroupCount")
    @ResponseWrapper(localName = "GroupCountResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GroupCountResponse")
    public int groupCount();

    @WebResult(name = "AllDefendersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllDefenders", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllDefenders")
    @WebMethod(operationName = "AllDefenders")
    @ResponseWrapper(localName = "AllDefendersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllDefendersResponse")
    public generatedcode.client.ArrayOfString allDefenders(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    @WebResult(name = "GameInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "GameInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GameInfo")
    @WebMethod(operationName = "GameInfo")
    @ResponseWrapper(localName = "GameInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.GameInfoResponse")
    public generatedcode.client.TGameInfo gameInfo(
        @WebParam(name = "iGameId", targetNamespace = "http://footballpool.dataaccess.eu")
        int iGameId
    );

    @WebResult(name = "AllCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllCards")
    @WebMethod(operationName = "AllCards")
    @ResponseWrapper(localName = "AllCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllCardsResponse")
    public generatedcode.client.ArrayOftCardInfo allCards();

    @WebResult(name = "AllMidFieldsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllMidFields", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllMidFields")
    @WebMethod(operationName = "AllMidFields")
    @ResponseWrapper(localName = "AllMidFieldsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllMidFieldsResponse")
    public generatedcode.client.ArrayOfString allMidFields(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    @WebResult(name = "AllGoalKeepersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllGoalKeepers", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllGoalKeepers")
    @WebMethod(operationName = "AllGoalKeepers")
    @ResponseWrapper(localName = "AllGoalKeepersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllGoalKeepersResponse")
    public generatedcode.client.ArrayOfString allGoalKeepers(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    @WebResult(name = "AllPlayersWithYellowOrRedCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "AllPlayersWithYellowOrRedCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayersWithYellowOrRedCards")
    @WebMethod(operationName = "AllPlayersWithYellowOrRedCards")
    @ResponseWrapper(localName = "AllPlayersWithYellowOrRedCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.AllPlayersWithYellowOrRedCardsResponse")
    public generatedcode.client.ArrayOftPlayersWithCards allPlayersWithYellowOrRedCards(
        @WebParam(name = "bSortedByName", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByName,
        @WebParam(name = "bSortedByYellowCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByYellowCards,
        @WebParam(name = "bSortedByRedCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByRedCards
    );

    @WebResult(name = "NextGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "NextGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.NextGame")
    @WebMethod(operationName = "NextGame")
    @ResponseWrapper(localName = "NextGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.NextGameResponse")
    public generatedcode.client.TGameInfo nextGame();

    @WebResult(name = "TopSelectedGoalScorersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    @RequestWrapper(localName = "TopSelectedGoalScorers", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TopSelectedGoalScorers")
    @WebMethod(operationName = "TopSelectedGoalScorers")
    @ResponseWrapper(localName = "TopSelectedGoalScorersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "generatedcode.client.TopSelectedGoalScorersResponse")
    public generatedcode.client.ArrayOftTopSelectedGoalScorer topSelectedGoalScorers(
        @WebParam(name = "iTopN", targetNamespace = "http://footballpool.dataaccess.eu")
        int iTopN
    );
}
