package cz.cvut.aos.printingserver.client;

/**
 * Please modify this class to meet your needs This class is not complete
 */
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.activation.DataHandler;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.3.1 Wed Nov 21 00:40:50 CET 2012
 * Generated source version: 2.3.1
 *
 */
public final class PrintingService_PrintingServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.printingserver.aos.cvut.cz/", "PrintingServiceImplService");

    private PrintingService_PrintingServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PrintingServiceImplService.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PrintingServiceImplService ss = new PrintingServiceImplService(wsdlURL, SERVICE_NAME);
        PrintingService port = ss.getPrintingServiceImplPort();
        BindingProvider bp = (BindingProvider) port;
        Binding binding = bp.getBinding();
        SOAPBinding soapBinding = (SOAPBinding) binding;
        soapBinding.setMTOMEnabled(true);

        {
            GregorianCalendar c = new GregorianCalendar();
            c.setTime(new Date());
            XMLGregorianCalendar date2 = DatatypeFactory.newInstance().newXMLGregorianCalendar(c);
            System.out.println("Invoking printAirTicket...");
            cz.cvut.aos.printingserver.client.Flight _printAirTicket_arg0 = new Flight(date2, 1999, "praha", "paris");
            cz.cvut.aos.printingserver.client.User _printAirTicket_arg1 = new User("Kacer", "Donald");
            cz.cvut.aos.printingserver.client.AirTicketCopy _printAirTicket__return = port.printAirTicket(_printAirTicket_arg0, _printAirTicket_arg1);
            System.out.println("printAirTicket.result=" + _printAirTicket__return);
            saveFile(_printAirTicket__return.getAirTicketData());
        }

        System.exit(0);
    }

    public static void saveFile(DataHandler file) {
        try {
            FileOutputStream out = new FileOutputStream("ticket.txt");
            file.writeTo(out);
            out.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
