package cz.cvut.aos.printingserver.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Nov 21 00:40:50 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://webservice.printingserver.aos.cvut.cz/", name = "PrintingService")
@XmlSeeAlso({ObjectFactory.class})
public interface PrintingService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "printAirTicket", targetNamespace = "http://webservice.printingserver.aos.cvut.cz/", className = "cz.cvut.aos.printingserver.client.PrintAirTicket")
    @WebMethod
    @ResponseWrapper(localName = "printAirTicketResponse", targetNamespace = "http://webservice.printingserver.aos.cvut.cz/", className = "cz.cvut.aos.printingserver.client.PrintAirTicketResponse")
    public cz.cvut.aos.printingserver.client.AirTicketCopy printAirTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        cz.cvut.aos.printingserver.client.Flight arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        cz.cvut.aos.printingserver.client.User arg1
    );
}
