
/*
 * 
 */

package cz.cvut.aos.printingserver.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Nov 21 00:40:50 CET 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "PrintingServiceImplService", 
                  wsdlLocation = "http://localhost:8081/PrintingServer/PrintingService?wsdl",
                  targetNamespace = "http://webservice.printingserver.aos.cvut.cz/") 
public class PrintingServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.printingserver.aos.cvut.cz/", "PrintingServiceImplService");
    public final static QName PrintingServiceImplPort = new QName("http://webservice.printingserver.aos.cvut.cz/", "PrintingServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/PrintingServer/PrintingService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8081/PrintingServer/PrintingService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PrintingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrintingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintingServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PrintingServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public PrintingServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PrintingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrintingService
     */
    @WebEndpoint(name = "PrintingServiceImplPort")
    public PrintingService getPrintingServiceImplPort() {
        return super.getPort(PrintingServiceImplPort, PrintingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintingService
     */
    @WebEndpoint(name = "PrintingServiceImplPort")
    public PrintingService getPrintingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PrintingServiceImplPort, PrintingService.class, features);
    }

}
