package cz.cvut.aos.flyingcompany.generatedcode.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Dec 12 14:09:34 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", name = "InterfaceWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface InterfaceWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSeat", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.ChangeSeat")
    @WebMethod
    @ResponseWrapper(localName = "changeSeatResponse", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.ChangeSeatResponse")
    public cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket changeSeat(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws UnknownAirTicketException_Exception, SeatNotAvailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findFlight", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.FindFlight")
    @WebMethod
    @ResponseWrapper(localName = "findFlightResponse", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.FindFlightResponse")
    public java.util.List<cz.cvut.aos.flyingcompany.generatedcode.client.Flight> findFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bookFlight", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.BookFlight")
    @WebMethod
    @ResponseWrapper(localName = "bookFlightResponse", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.BookFlightResponse")
    public cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket bookFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo arg1
    ) throws UnsupportedPaymentTypeException_Exception, UnknownAccountException_Exception, FlightCapacityExceededException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "printAirTicket", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.PrintAirTicket")
    @WebMethod
    @ResponseWrapper(localName = "printAirTicketResponse", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.PrintAirTicketResponse")
    public cz.cvut.aos.flyingcompany.generatedcode.client.AirTicketCopy printAirTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1
    ) throws UnknownAirTicketException_Exception, UnknownAccountException_Exception, PrintingException_Exception;

    @RequestWrapper(localName = "cancelFlight", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.CancelFlight")
    @WebMethod
    @ResponseWrapper(localName = "cancelFlightResponse", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/", className = "cz.cvut.aos.flyingcompany.generatedcode.client.CancelFlightResponse")
    public void cancelFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws UnknownAirTicketException_Exception;
}
