package cz.cvut.aos.flyingcompany.generatedcode.client;

/**
 * Please modify this class to meet your needs This class is not complete
 */
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.activation.DataHandler;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1 Wed Dec 12 14:09:34 CET 2012
 * Generated source version: 2.3.1
 *
 */
public final class InterfaceWebService_InterfaceWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.interfaceserver.aos.cvut.cz/", "InterfaceWebServiceImplService");

    private InterfaceWebService_InterfaceWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = InterfaceWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        InterfaceWebServiceImplService ss = new InterfaceWebServiceImplService(wsdlURL, SERVICE_NAME);
        InterfaceWebService port = ss.getInterfaceWebServiceImplPort();

        System.out.println("---------------------------------------------------------------------------");

        {
            System.out.println("Invoking findFlight...");
            java.lang.String _findFlight_arg0 = "prague";
            java.lang.String _findFlight_arg1 = "berlin";
            java.lang.String _findFlight_arg2 = "2012-12-20 12:00:00";
            java.util.List<cz.cvut.aos.flyingcompany.generatedcode.client.Flight> _findFlight__return = port.findFlight(_findFlight_arg0, _findFlight_arg1, _findFlight_arg2);
            System.out.println("findFlight.result=" + _findFlight__return);
        }


        System.out.println("---------------------------------------------------------------------------");

        {
            System.out.println("Invoking bookFlight...");
            java.lang.Long _bookFlight_arg0 = 2L;
            cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo _bookFlight_arg1 = new PaymentInfo(123L, 456L, "bank");
            try {
                cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket _bookFlight__return = port.bookFlight(_bookFlight_arg0, _bookFlight_arg1);
                System.out.println("bookFlight.result=" + _bookFlight__return);

            } catch (UnsupportedPaymentTypeException_Exception e) {
                System.out.println("Expected exception: UnsupportedPaymentTypeException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (FlightCapacityExceededException_Exception e) {
                System.out.println("Expected exception: FlightCapacityExceededException has occurred.");
                System.out.println(e.toString());
            }
        }
        
        System.out.println("---------------------------------------------------------------------------");

        {
            System.out.println("Invoking bookFlight expecting unknown account exception...");
            java.lang.Long _bookFlight_arg0 = 2L;
            cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo _bookFlight_arg1 = new PaymentInfo(123L, 666L, "bank");
            try {
                cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket _bookFlight__return = port.bookFlight(_bookFlight_arg0, _bookFlight_arg1);
                System.out.println("bookFlight.result=" + _bookFlight__return);

            } catch (UnsupportedPaymentTypeException_Exception e) {
                System.out.println("Expected exception: UnsupportedPaymentTypeException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (FlightCapacityExceededException_Exception e) {
                System.out.println("Expected exception: FlightCapacityExceededException has occurred.");
                System.out.println(e.toString());
            }
        }

        System.out.println("---------------------------------------------------------------------------");

        {
            System.out.println("Invoking bookFlight expecting unsupported payment type exception...");
            java.lang.Long _bookFlight_arg0 = 2L;
            cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo _bookFlight_arg1 = new PaymentInfo(123L, 456L, "paypal");
            try {
                cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket _bookFlight__return = port.bookFlight(_bookFlight_arg0, _bookFlight_arg1);
                System.out.println("bookFlight.result=" + _bookFlight__return);

            } catch (UnsupportedPaymentTypeException_Exception e) {
                System.out.println("Expected exception: UnsupportedPaymentTypeException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (FlightCapacityExceededException_Exception e) {
                System.out.println("Expected exception: FlightCapacityExceededException has occurred.");
                System.out.println(e.toString());
            }
        }

        System.out.println("---------------------------------------------------------------------------");

        {
            cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket bookedFlightAirTicket = null;

            System.out.println("Invoking bookFlight...");
            java.lang.Long _bookFlight_arg0 = 2L;
            cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo _bookFlight_arg1 = new PaymentInfo(123L, 456L, "bank");
            try {
                bookedFlightAirTicket = port.bookFlight(_bookFlight_arg0, _bookFlight_arg1);
                System.out.println("bookFlight.result=" + bookedFlightAirTicket);

            } catch (UnsupportedPaymentTypeException_Exception e) {
                System.out.println("Expected exception: UnsupportedPaymentTypeException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (FlightCapacityExceededException_Exception e) {
                System.out.println("Expected exception: FlightCapacityExceededException has occurred.");
                System.out.println(e.toString());
            }
            
            cz.cvut.aos.flyingcompany.generatedcode.client.AirTicketCopy airTicketCopy = null;
            System.out.println("Invoking printAirTicket...");
            java.lang.Long _printAirTicket_arg0 = bookedFlightAirTicket.getId();
            java.lang.Long _printAirTicket_arg1 = 123L;
            try {
                airTicketCopy = port.printAirTicket(_printAirTicket_arg0, _printAirTicket_arg1);
                System.out.println("printAirTicket.result=" + airTicketCopy);

            } catch (UnknownAirTicketException_Exception e) {
                System.out.println("Expected exception: UnknownAirTicketException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (PrintingException_Exception e) {
                System.out.println("Expected exception: PrintingException has occurred.");
                System.out.println(e.toString());
            }
            DataHandler file = airTicketCopy.getAirTicketData();
        try {
            File f = new File("newticket.txt");
            f.createNewFile();
            FileOutputStream out = new FileOutputStream(f);
            file.writeTo(out);
            out.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        }

        System.out.println("---------------------------------------------------------------------------");

        {
            
            cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket bookedFlightAirTicket = null;

            System.out.println("Invoking bookFlight...");
            java.lang.Long _bookFlight_arg0 = 2L;
            cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo _bookFlight_arg1 = new PaymentInfo(123L, 456L, "bank");
            try {
                bookedFlightAirTicket = port.bookFlight(_bookFlight_arg0, _bookFlight_arg1);
                System.out.println("bookFlight.result=" + bookedFlightAirTicket);

            } catch (UnsupportedPaymentTypeException_Exception e) {
                System.out.println("Expected exception: UnsupportedPaymentTypeException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (FlightCapacityExceededException_Exception e) {
                System.out.println("Expected exception: FlightCapacityExceededException has occurred.");
                System.out.println(e.toString());
            }
            
            System.out.println("Invoking changeSeat...");
            java.lang.Long _changeSeat_arg0 = bookedFlightAirTicket.getId();
            int _changeSeat_arg1 = 46;
            System.out.println(".. with param: "+46);
            try {
                cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket _changeSeat__return = port.changeSeat(_changeSeat_arg0, _changeSeat_arg1);
                System.out.println("changeSeat.result=" + _changeSeat__return);

            } catch (UnknownAirTicketException_Exception e) {
                System.out.println("Expected exception: UnknownAirTicketException has occurred.");
                System.out.println(e.toString());
            } catch (SeatNotAvailable_Exception e) {
                System.out.println("Expected exception: SeatNotAvailable has occurred.");
                System.out.println(e.toString());
            }
        }

        System.out.println("---------------------------------------------------------------------------");

        {
            cz.cvut.aos.flyingcompany.generatedcode.client.AirTicket bookedFlightAirTicket = null;

            System.out.println("Invoking bookFlight...");
            java.lang.Long _bookFlight_arg0 = 2L;
            cz.cvut.aos.flyingcompany.generatedcode.client.PaymentInfo _bookFlight_arg1 = new PaymentInfo(123L, 456L, "bank");
            try {
                bookedFlightAirTicket = port.bookFlight(_bookFlight_arg0, _bookFlight_arg1);
                System.out.println("bookFlight.result=" + bookedFlightAirTicket);

            } catch (UnsupportedPaymentTypeException_Exception e) {
                System.out.println("Expected exception: UnsupportedPaymentTypeException has occurred.");
                System.out.println(e.toString());
            } catch (UnknownAccountException_Exception e) {
                System.out.println("Expected exception: UnknownAccountException has occurred.");
                System.out.println(e.toString());
            } catch (FlightCapacityExceededException_Exception e) {
                System.out.println("Expected exception: FlightCapacityExceededException has occurred.");
                System.out.println(e.toString());
            }
            
            System.out.println("Invoking cancelFlight...");
            java.lang.Long _cancelFlight_arg0 = bookedFlightAirTicket.getId();
            try {
                port.cancelFlight(_cancelFlight_arg0);

            } catch (UnknownAirTicketException_Exception e) {
                System.out.println("Expected exception: UnknownAirTicketException has occurred.");
                System.out.println(e.toString());
            }
        }

        System.exit(0);
    }
}
