
package cz.cvut.aos.flyingcompany.generatedcode.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Dec 12 14:09:34 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "SeatNotAvailable", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/")
public class SeatNotAvailable_Exception extends Exception {
    public static final long serialVersionUID = 20121212140934L;
    
    private cz.cvut.aos.flyingcompany.generatedcode.client.SeatNotAvailable seatNotAvailable;

    public SeatNotAvailable_Exception() {
        super();
    }
    
    public SeatNotAvailable_Exception(String message) {
        super(message);
    }
    
    public SeatNotAvailable_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SeatNotAvailable_Exception(String message, cz.cvut.aos.flyingcompany.generatedcode.client.SeatNotAvailable seatNotAvailable) {
        super(message);
        this.seatNotAvailable = seatNotAvailable;
    }

    public SeatNotAvailable_Exception(String message, cz.cvut.aos.flyingcompany.generatedcode.client.SeatNotAvailable seatNotAvailable, Throwable cause) {
        super(message, cause);
        this.seatNotAvailable = seatNotAvailable;
    }

    public cz.cvut.aos.flyingcompany.generatedcode.client.SeatNotAvailable getFaultInfo() {
        return this.seatNotAvailable;
    }
}
