
package cz.cvut.aos.flyingcompany.generatedcode.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Dec 12 14:09:34 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "UnknownAirTicketException", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/")
public class UnknownAirTicketException_Exception extends Exception {
    public static final long serialVersionUID = 20121212140934L;
    
    private cz.cvut.aos.flyingcompany.generatedcode.client.UnknownAirTicketException unknownAirTicketException;

    public UnknownAirTicketException_Exception() {
        super();
    }
    
    public UnknownAirTicketException_Exception(String message) {
        super(message);
    }
    
    public UnknownAirTicketException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownAirTicketException_Exception(String message, cz.cvut.aos.flyingcompany.generatedcode.client.UnknownAirTicketException unknownAirTicketException) {
        super(message);
        this.unknownAirTicketException = unknownAirTicketException;
    }

    public UnknownAirTicketException_Exception(String message, cz.cvut.aos.flyingcompany.generatedcode.client.UnknownAirTicketException unknownAirTicketException, Throwable cause) {
        super(message, cause);
        this.unknownAirTicketException = unknownAirTicketException;
    }

    public cz.cvut.aos.flyingcompany.generatedcode.client.UnknownAirTicketException getFaultInfo() {
        return this.unknownAirTicketException;
    }
}
