
package cz.cvut.aos.flyingcompany.generatedcode.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Dec 12 14:09:34 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "UnsupportedPaymentTypeException", targetNamespace = "http://webservice.interfaceserver.aos.cvut.cz/")
public class UnsupportedPaymentTypeException_Exception extends Exception {
    public static final long serialVersionUID = 20121212140934L;
    
    private cz.cvut.aos.flyingcompany.generatedcode.client.UnsupportedPaymentTypeException unsupportedPaymentTypeException;

    public UnsupportedPaymentTypeException_Exception() {
        super();
    }
    
    public UnsupportedPaymentTypeException_Exception(String message) {
        super(message);
    }
    
    public UnsupportedPaymentTypeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedPaymentTypeException_Exception(String message, cz.cvut.aos.flyingcompany.generatedcode.client.UnsupportedPaymentTypeException unsupportedPaymentTypeException) {
        super(message);
        this.unsupportedPaymentTypeException = unsupportedPaymentTypeException;
    }

    public UnsupportedPaymentTypeException_Exception(String message, cz.cvut.aos.flyingcompany.generatedcode.client.UnsupportedPaymentTypeException unsupportedPaymentTypeException, Throwable cause) {
        super(message, cause);
        this.unsupportedPaymentTypeException = unsupportedPaymentTypeException;
    }

    public cz.cvut.aos.flyingcompany.generatedcode.client.UnsupportedPaymentTypeException getFaultInfo() {
        return this.unsupportedPaymentTypeException;
    }
}
