
/*
 * 
 */

package cz.cvut.aos.paymentservice.paymentserviceclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Nov 22 15:23:18 CET 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "PaymentWebServiceImplService", 
                  wsdlLocation = "http://localhost:8081/PaymentServer/PaymentService?wsdl",
                  targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/") 
public class PaymentWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.paymentserver.aos.cvut.cz/", "PaymentWebServiceImplService");
    public final static QName PaymentWebServiceImplPort = new QName("http://webservice.paymentserver.aos.cvut.cz/", "PaymentWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/PaymentServer/PaymentService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8081/PaymentServer/PaymentService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PaymentWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PaymentWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public PaymentWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PaymentWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentWebService
     */
    @WebEndpoint(name = "PaymentWebServiceImplPort")
    public PaymentWebService getPaymentWebServiceImplPort() {
        return super.getPort(PaymentWebServiceImplPort, PaymentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentWebService
     */
    @WebEndpoint(name = "PaymentWebServiceImplPort")
    public PaymentWebService getPaymentWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PaymentWebServiceImplPort, PaymentWebService.class, features);
    }

}
