package cz.cvut.aos.paymentservice.paymentserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Nov 22 15:23:18 CET 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/", name = "PaymentWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "payWithBankAccount", targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/", className = "cz.cvut.aos.paymentservice.paymentserviceclient.PayWithBankAccount")
    @WebMethod
    @ResponseWrapper(localName = "payWithBankAccountResponse", targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/", className = "cz.cvut.aos.paymentservice.paymentserviceclient.PayWithBankAccountResponse")
    public cz.cvut.aos.paymentservice.paymentserviceclient.Payment payWithBankAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    ) throws UnknownAccountException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "payWithCreditCard", targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/", className = "cz.cvut.aos.paymentservice.paymentserviceclient.PayWithCreditCard")
    @WebMethod
    @ResponseWrapper(localName = "payWithCreditCardResponse", targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/", className = "cz.cvut.aos.paymentservice.paymentserviceclient.PayWithCreditCardResponse")
    public cz.cvut.aos.paymentservice.paymentserviceclient.Payment payWithCreditCard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    ) throws UnknownAccountException_Exception;
}
