
package cz.cvut.aos.paymentservice.paymentserviceclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Nov 22 15:23:18 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "UnknownAccountException", targetNamespace = "http://webservice.paymentserver.aos.cvut.cz/")
public class UnknownAccountException_Exception extends Exception {
    public static final long serialVersionUID = 20121122152318L;
    
    private cz.cvut.aos.paymentservice.paymentserviceclient.UnknownAccountException unknownAccountException;

    public UnknownAccountException_Exception() {
        super();
    }
    
    public UnknownAccountException_Exception(String message) {
        super(message);
    }
    
    public UnknownAccountException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownAccountException_Exception(String message, cz.cvut.aos.paymentservice.paymentserviceclient.UnknownAccountException unknownAccountException) {
        super(message);
        this.unknownAccountException = unknownAccountException;
    }

    public UnknownAccountException_Exception(String message, cz.cvut.aos.paymentservice.paymentserviceclient.UnknownAccountException unknownAccountException, Throwable cause) {
        super(message, cause);
        this.unknownAccountException = unknownAccountException;
    }

    public cz.cvut.aos.paymentservice.paymentserviceclient.UnknownAccountException getFaultInfo() {
        return this.unknownAccountException;
    }
}
