
package filesending.base64.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 10:11:10 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

public final class SendFileIface_SendFileIfaceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.base64.filesending/", "SendFileIfaceImplService");

    private SendFileIface_SendFileIfaceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SendFileIfaceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SendFileIfaceImplService ss = new SendFileIfaceImplService(wsdlURL, SERVICE_NAME);
        SendFileIface port = ss.getSendFileIfaceImplPort();  
        
        {
        System.out.println("Invoking sendFile...");
        byte [] array = new byte[]{1,2,3,4};
        byte[] _sendFile_arg0 = array;
        port.sendFile(_sendFile_arg0);


        }

        System.exit(0);
    }

}
