
/*
 * 
 */

package filesending.base64.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 10:11:10 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SendFileIfaceImplService", 
                  wsdlLocation = "http://localhost:8099/cxf_spring/SendFile?wsdl",
                  targetNamespace = "http://server.base64.filesending/") 
public class SendFileIfaceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://server.base64.filesending/", "SendFileIfaceImplService");
    public final static QName SendFileIfaceImplPort = new QName("http://server.base64.filesending/", "SendFileIfaceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8099/cxf_spring/SendFile?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8099/cxf_spring/SendFile?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SendFileIfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendFileIfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendFileIfaceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SendFileIfaceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public SendFileIfaceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SendFileIfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendFileIface
     */
    @WebEndpoint(name = "SendFileIfaceImplPort")
    public SendFileIface getSendFileIfaceImplPort() {
        return super.getPort(SendFileIfaceImplPort, SendFileIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendFileIface
     */
    @WebEndpoint(name = "SendFileIfaceImplPort")
    public SendFileIface getSendFileIfaceImplPort(WebServiceFeature... features) {
        return super.getPort(SendFileIfaceImplPort, SendFileIface.class, features);
    }

}
