package concatsecuritydemo.server;

import java.util.HashMap;
import java.util.Map;
import javax.xml.ws.Endpoint;
import org.apache.cxf.jaxws.EndpointImpl;

import org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor;
import org.apache.ws.security.handler.WSHandlerConstants;

/**
 * This class was generated by Apache CXF 2.3.1 Thu Nov 08 10:32:54 CET 2012
 * Generated source version: 2.3.1
 *
 */
public class ConcatService_ConcatSOAP_Server {

    protected ConcatService_ConcatSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ConcatServiceImpl();
        String address = "http://localhost:8082/";
        Map<String, Object> properties = new HashMap<String, Object>();

//properties.put(SecurityConstants.SIGNATURE_PROPERTIES, "crypto.properties");
        EndpointImpl jaxWsEndpoint = (EndpointImpl) Endpoint.publish(address, implementor);
        org.apache.cxf.endpoint.Endpoint cxfEndpoint = jaxWsEndpoint.getServer().getEndpoint();

        properties.put(WSHandlerConstants.ACTION, "Signature");
        properties.put(WSHandlerConstants.USER, "c1");
        properties.put(WSHandlerConstants.PW_CALLBACK_CLASS, ServerPasswordCallback.class.getName());
        properties.put(WSHandlerConstants.SIG_PROP_FILE, "crypto.properties");

        WSS4JInInterceptor wssIn = new WSS4JInInterceptor(properties);
        cxfEndpoint.getInInterceptors().add(wssIn);
    }

    public static void main(String args[]) throws Exception {
        new ConcatService_ConcatSOAP_Server();
        System.out.println("Server ready...");

        Thread.sleep(10 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
