
package edu.tomy.aoslab04;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 11 10:49:12 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

public final class SumServiceIface_SumServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://aoslab04.tomy.edu/", "SumServiceService");

    private SumServiceIface_SumServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SumServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SumServiceService ss = new SumServiceService(wsdlURL, SERVICE_NAME);
        SumServiceIface port = ss.getSumServicePort();  
        
        {
        System.out.println("Invoking getSum...");
        int _getSum_arg0 = 3;
        int _getSum_arg1 = 7;
        int _getSum__return = port.getSum(_getSum_arg0, _getSum_arg1);
        System.out.println("getSum.result=" + _getSum__return);


        }

        System.exit(0);
    }

}
