
/*
 * 
 */

package edu.tomy.aoslab04;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 11 10:49:12 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SumServiceService", 
                  wsdlLocation = "http://localhost:8080/aos-lab04/SumService?wsdl",
                  targetNamespace = "http://aoslab04.tomy.edu/") 
public class SumServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://aoslab04.tomy.edu/", "SumServiceService");
    public final static QName SumServicePort = new QName("http://aoslab04.tomy.edu/", "SumServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/aos-lab04/SumService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/aos-lab04/SumService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SumServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SumServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SumServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public SumServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SumServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SumServiceIface
     */
    @WebEndpoint(name = "SumServicePort")
    public SumServiceIface getSumServicePort() {
        return super.getPort(SumServicePort, SumServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SumServiceIface
     */
    @WebEndpoint(name = "SumServicePort")
    public SumServiceIface getSumServicePort(WebServiceFeature... features) {
        return super.getPort(SumServicePort, SumServiceIface.class, features);
    }

}
