package division.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 09:50:43 CEST 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://testing/", name = "DivisionServiceIface")
@XmlSeeAlso({ObjectFactory.class})
public interface DivisionServiceIface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://testing/", className = "division.client.Divide")
    @WebMethod
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://testing/", className = "division.client.DivideResponse")
    public float divide(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1
    ) throws DivisionByZeroExceptionException;
}
