
/*
 * 
 */

package division.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 09:50:43 CEST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "DivisionServiceIfaceImplService", 
                  wsdlLocation = "http://localhost:8083/cxf_spring/DivisionService?wsdl",
                  targetNamespace = "http://division/") 
public class DivisionServiceIfaceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://division/", "DivisionServiceIfaceImplService");
    public final static QName DivisionServiceIfaceImplPort = new QName("http://division/", "DivisionServiceIfaceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8083/cxf_spring/DivisionService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8083/cxf_spring/DivisionService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DivisionServiceIfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DivisionServiceIfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DivisionServiceIfaceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DivisionServiceIfaceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public DivisionServiceIfaceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DivisionServiceIfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DivisionServiceIface
     */
    @WebEndpoint(name = "DivisionServiceIfaceImplPort")
    public DivisionServiceIface getDivisionServiceIfaceImplPort() {
        return super.getPort(DivisionServiceIfaceImplPort, DivisionServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DivisionServiceIface
     */
    @WebEndpoint(name = "DivisionServiceIfaceImplPort")
    public DivisionServiceIface getDivisionServiceIfaceImplPort(WebServiceFeature... features) {
        return super.getPort(DivisionServiceIfaceImplPort, DivisionServiceIface.class, features);
    }

}
