
package division.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Oct 25 09:50:43 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "DivisionByZeroException", targetNamespace = "http://testing/")
public class DivisionByZeroExceptionException extends Exception {
    public static final long serialVersionUID = 20121025095043L;
    
    private division.client.DivisionByZeroException divisionByZeroException;

    public DivisionByZeroExceptionException() {
        super();
    }
    
    public DivisionByZeroExceptionException(String message) {
        super(message);
    }
    
    public DivisionByZeroExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public DivisionByZeroExceptionException(String message, division.client.DivisionByZeroException divisionByZeroException) {
        super(message);
        this.divisionByZeroException = divisionByZeroException;
    }

    public DivisionByZeroExceptionException(String message, division.client.DivisionByZeroException divisionByZeroException, Throwable cause) {
        super(message, cause);
        this.divisionByZeroException = divisionByZeroException;
    }

    public division.client.DivisionByZeroException getFaultInfo() {
        return this.divisionByZeroException;
    }
}
